### ISSUE TITLE
Problem with WeatherXM D1 precipitation rate on the WG1200 gateway screen

### ISSUE THREAD

**Issue by Chris6175** [WeatherXM/wxm-android#294]
## **Describe the bug**
I have the WXM D1 version. It records the total daily precipitation fine as total but the precipitation rate stays at 0 all the time. When it's raining I see daily precipitation going up but the precipitation rate stays at 0. On the gateway (WG1200) screen as well as on the app screen.
It's not related to Android or IOS specifically, because the rate also shows 0 on the gateway screen itself. And also, in the Discord channel people with Android and with IOS have reported the same problem. I'm guessing it's a bug in the D1 firmware.

### **How To Reproduce**
When you have a D1, just look at your Gateway (WG1200) screen when it rains. You will see the precipitation rate staying at 0.

### **Expected behavior**
I expect the precipitation rate to be not 0 when it rains.

![Screenshot_20240906_113927_WeatherXM](https://github.com/user-attachments/assets/3c7280e5-1533-43ab-a1f8-f19de26d4709)

### **Additional context**
None

**Comment by PavlosTze** [comment]
Hello @Chris6175 , thank you for reporting this bug. I confirm that we are aware of it and the fix will be included in a future firmware version of D1.

**Comment by Chris6175** [comment]
Hello,

When can we expect a firmware update to resolve this issue ? 
Because precipitation rate is actually a really interesting weather parameter, and it's a pity we can't see it yet.

best regards,
Chris.

**Comment by PavlosTze** [comment]
Hello Chris,

We are testing it internally and we will have more info to share soon.

**Comment by NikosTsiligaridis** [comment]
The firmware is expected to be rolled out within the following few das

**Comment by Chris6175** [comment]
Great, i'll be looking out for that update.

**Comment by NikosTsiligaridis** [comment]
Update has been rolled out, all devices will receive it automatically.

**Comment by Chris6175** [comment]
Thanks. I'm curious now for the first rainfall ;-)
What the new firmware version ?
