### ISSUE TITLE
Precipitation rate still not showing on all D1 weather stations

### ISSUE THREAD

**Issue by Chris6175** [WeatherXM/wxm-android#379]
## **Describe the bug**

Since the firmware update (0.1.15) that happened on the D1 a little more than a week ago, I started to consult the precipitation rate, to see if it was really registering now. At first I wasn't sure, since the rainfall was pretty light, but now today the rainfall was quite heavy and the precipitation rate still didn't move at all. So I think we can conclude the issue with the precipitation rate still isn't fixed. 

I checked the map with all weather stations and i looked up some D1 weather stations. ALL of the D1 weather stations still have the same issue. Those that recorded rainfall during the past days, still had the precipitation rate always staying at zero all the time. Just see for yourself in the explorer map and look up D1 weather stations and look at their data, and you will see for yourself...

I really hope it's only a firmware issue, and not a problem with the D1 stations themselves not able to register a precipitation rate ? Because the first thing can be fixed, the latter is a whole other issue...

### **How To Reproduce**

When you have a D1, just look at your Gateway (WG1200) screen when it rains. You will see the precipitation rate still staying at 0. Or look at the historical data in the app (for any D1 weather station for that matter), and you will see the precipitation rate always stayed zero during all the time that it rained.

### **Expected behavior**

I expect the precipitation rate to be not 0 when it rains.

![Image](https://github.com/user-attachments/assets/132e73da-5ec3-4e15-a280-77cc9e474e46)

### **Additional context**

It's not related to Android or IOS, or any device for that matter, it's a problem related to all D1 weather stations.

Some practical examples of D1 weather stations with rainy days  : 

**Name D1 station**                                                    **Rainy day example**
                                                  
Crazy Leather Fog -                                                   20/10/2024                            
Rural Cobalt Atmosphere -                                      18/10/2024
Rural Cornflower Dust -                                               21/10/2024
Colossal Sangria Sandstorm -                                   18/10/2024
Recumbent Brunette Stratocumulus -                       20/10/2024

**Comment by 1000ouz** [comment]
I can state same issue on my D1 (firmware 0.1.15), no precipitation rate shown even though raining coninously.

**Comment by Chris6175** [comment]
I can confirm that the precipitation rate is now showing in the graphics.
However the max rate is still staying at 0.0mm/h and is not adapting to the max recorded rate of the grapic line.
![Image](https://github.com/user-attachments/assets/37679eaf-2254-4c0a-9a43-e014abbc9087)

**Comment by Chris6175** [comment]
Some practical examples : 

Rural Cornflower Dust - 12/11/2024
Crazy Leather Frog - 11/11/2024
Rural Cornflower Dust - 11/11/2024

**Comment by Chris6175** [comment]
It also even seems that the "Daily" mm/h is also staying at 0 as well.

Practical examples of this : 
Crazy Leather Frog - 11/11/2024
Rural Cobalt Atmosphere - 11/11/2024

**Comment by Chris6175** [comment]
It also seems that the "Daily" number is also staying at 0.0mm/h, even though it rained.
![Image](https://github.com/user-attachments/assets/64b7a1b9-479e-4517-b8c0-8de7fa8376c8)


Practical examples of this : 
Crazy Leather Frog - 11/11/2024
Rural Cobalt Atmostphere - 11/11/2024

**Comment by Chris6175** [comment]
So even though, all the graphics are now working for the precipitation, both numbers ("Max Rate" & "Daily") above the graphics, still stay at 0.

**Comment by PavlosTze** [comment]
Hey @Chris6175 , the charts show 0.0 in the labels because the time selected is the 00:00 (the start of the chart) as can be seen above the labels.
![Image](https://github.com/user-attachments/assets/f69ca40b-a0e7-4b03-8086-e59aac6375fe)

If you select a different time in the chart having precipitation, the labels will be adjusted automatically.

Could you please verify this so then we can close this issue?

**Comment by Chris6175** [comment]
Hello,
Indeed, you are correct. In that case, it working fine.
You can close it, thank you.

best regards,
Chris.
